--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2022 9:30:08 AM
-- Server version: 10.4.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ordermanagment;

--
-- Drop table `migrations`
--
DROP TABLE IF EXISTS migrations;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `addresses`
--
DROP TABLE IF EXISTS addresses;

--
-- Drop table `costumers`
--
DROP TABLE IF EXISTS costumers;

--
-- Drop table `owners`
--
DROP TABLE IF EXISTS owners;

--
-- Drop table `permission_user`
--
DROP TABLE IF EXISTS permission_user;

--
-- Drop table `permissions`
--
DROP TABLE IF EXISTS permissions;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `transportations`
--
DROP TABLE IF EXISTS transportations;

--
-- Drop table `years`
--
DROP TABLE IF EXISTS years;

--
-- Set default database
--
USE ordermanagment;

--
-- Create table `years`
--
CREATE TABLE years (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  start date NOT NULL,
  end date NOT NULL,
  defult tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_persian_ci;

--
-- Create table `transportations`
--
CREATE TABLE transportations (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(30) NOT NULL,
  manager varchar(30) NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  is_active tinyint(1) NOT NULL,
  transportation_id int(10) UNSIGNED DEFAULT NULL,
  year_id int(10) UNSIGNED DEFAULT NULL,
  remember_token varchar(100) DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT users_ibfk_1 FOREIGN KEY (transportation_id)
REFERENCES transportations (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT users_ibfk_2 FOREIGN KEY (year_id)
REFERENCES years (id) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Create table `permissions`
--
CREATE TABLE permissions (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  permit varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 18,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `permission_user`
--
CREATE TABLE permission_user (
  user_id int(10) UNSIGNED NOT NULL,
  permission_id int(10) UNSIGNED NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (user_id, permission_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE permission_user
ADD CONSTRAINT permission_user_ibfk_1 FOREIGN KEY (user_id)
REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE permission_user
ADD CONSTRAINT permission_user_ibfk_2 FOREIGN KEY (permission_id)
REFERENCES permissions (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `owners`
--
CREATE TABLE owners (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  national_id varchar(11) NOT NULL,
  zip_code varchar(10) NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `costumers`
--
CREATE TABLE costumers (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name varchar(20) NOT NULL,
  last_name varchar(100) NOT NULL,
  description varchar(100) DEFAULT NULL,
  national_code varchar(11) NOT NULL,
  phone_num varchar(200) DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 320,
AVG_ROW_LENGTH = 321,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `addresses`
--
CREATE TABLE addresses (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) binary NOT NULL,
  phone_number varchar(11) binary DEFAULT NULL,
  zip_code varchar(10) binary DEFAULT NULL,
  address varchar(500) binary NOT NULL,
  is_default tinyint(1) NOT NULL DEFAULT 0,
  costumer_id int(10) UNSIGNED NOT NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  updated_at timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1085,
AVG_ROW_LENGTH = 320,
CHARACTER SET utf8,
COLLATE utf8_bin;

--
-- Create foreign key
--
ALTER TABLE addresses
ADD CONSTRAINT addresses_ibfk_1 FOREIGN KEY (costumer_id)
REFERENCES costumers (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `orders`
--
CREATE TABLE orders (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_num int(11) NOT NULL,
  amount int(11) NOT NULL,
  description varchar(255) DEFAULT NULL,
  date date NOT NULL,
  is_certain tinyint(1) NOT NULL DEFAULT 1,
  is_viewed tinyint(1) NOT NULL DEFAULT 0,
  costumer_id int(10) UNSIGNED NOT NULL,
  address_id int(10) UNSIGNED DEFAULT NULL,
  transportation_id int(10) UNSIGNED NOT NULL,
  owner_id int(10) UNSIGNED NOT NULL,
  year_id int(10) UNSIGNED NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1177,
AVG_ROW_LENGTH = 102,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_2 FOREIGN KEY (owner_id)
REFERENCES owners (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_4 FOREIGN KEY (year_id)
REFERENCES years (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_6 FOREIGN KEY (costumer_id)
REFERENCES costumers (id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_7 FOREIGN KEY (address_id)
REFERENCES addresses (id) ON UPDATE SET NULL;

--
-- Create foreign key
--
ALTER TABLE orders
ADD CONSTRAINT orders_ibfk_8 FOREIGN KEY (transportation_id)
REFERENCES transportations (id) ON UPDATE CASCADE;

--
-- Create table `migrations`
--
CREATE TABLE migrations (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration varchar(255) NOT NULL,
  batch int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;